baseURL = "https://hangyan.github.io/"
title = "涯余的博客"
locale = "zh-cn"
theme = "hugo-xmin"
enableRobotsTXT = true
enableEmoji = true
preserveTaxonomyNames = true    # keep Chinese tag/category names in URLs

[params]
  description = "CyberLife."
  footer = "&copy; [涯余](https://hangyan.github.io/) 2013 -- {Year} | [GitHub](https://github.com/hangyan) | [Email](mailto:hang.yan@hotmail.com)"

  [params.author]
    name = "涯余"
    email = "hang.yan@hotmail.com"

[[menu.main]]
  name = "Home"
  url = ""
  weight = 1
[[menu.main]]
  name = "Archives"
  url = "post/"
  weight = 2
[[menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 3
[[menu.main]]
  name = "Categories"
  url = "categories/"
  weight = 4
[[menu.main]]
  name = "Subscribe"
  url = "index.xml"
  weight = 5

[markup]
  [markup.goldmark.renderer]
    unsafe = true
